//{{NO_DEPENDENCIES}}
// Arquivo de inclusão gerado pelo Microsoft Visual C++.
// Usado por WindowsProject.rc
//
#define IDI_APP_ICON                    1
#define IDC_MYICON                      2
#define IDD_DIALOG1                     101
#define IDS_APP_TITLE                   102
#define IDD_WINDOWSPROJECT_DIALOG       103
#define IDD_ABOUTBOX                    104
#define IDM_ABOUT                       105
#define IDM_EXIT                        106
#define IDI_WINDOWSPROJECT              107
#define IDI_SMALL                       108
#define IDC_WINDOWSPROJECT              109
#define IDI_ICON1                       136
#define IDI_ICON                        136
#define IDI_ICON2                       138
#define IDC_CREME                       145
#define IDB_ESTEIRA                     150
#define IDD_WELCOME                     156
#define IDC_POTE                        160
#define IDI_ICON3                       162
#define IDB_TANQUE                      163
#define IDB_TANQUEMISTURA               164
#define IDB_CANO1                       165
#define IDB_CANO2                       166
#define IDB_CANO3                       167
#define IDB_pote                        169
#define IDB_VALVULAON                   172
#define IDB_VALVULAOF                   175
#define IDI_ICONE                       176
#define IDB_MIX1                        177
#define IDB_BITMAP2                     178
#define IDB_MIX2                        178
#define IDB_SPLASH                      179
#define IDB_GOTAS                       180
#define IDB_LOGO                        181
#define IDB_BITMAP1                     183
#define IDB_WARNING                     183
#define IDC_DESPERDICIO                 1001
#define IDC_VOLUME                      1002
#define IDC_SLIDER1                     1002
#define IDC_PH                          1003
#define IDC_DESPERDICIO2                1003
#define IDC_TEMP                        1004
#define IDC_RESET                       1005
#define IDC_PROGRESSTEMP                1005
#define IDC_CONNECT                     1006
#define IDC_RADIOTEMP                   1006
#define IDC_RADIOPH                     1007
#define IDC_TEMP2                       1008
#define IDC_RADIO3                      1011
#define IDC_MORANGO                     1015
#define IDC_CHOCOLATE                   1016
#define IDC_EDITSERIAL                  1019
#define IDC_EDIT_SERIAL                 1020
#define IDC_CHECK1                      1020
#define IDC_CHECKMORANGO                1020
#define IDC_ESTEIRAON                   1021
#define IDC_TANQUECREME                 1022
#define IDC_TANQUEMORANGO               1023
#define IDC_TANQUECHOCOLATE             1024
#define IDC_CANO2                       1025
#define IDC_CANO1C                      1026
#define IDC_CANO1CHO                    1027
#define IDC_CANO3CHO                    1028
#define IDC_CANO1M                      1029
#define IDC_CANO2M                      1030
#define IDC_PROGRESSMIXER               1031
#define IDC_MIXER                       1032
#define IDC_TPHCREME                    1033
#define IDC_TPHMORANGO                  1034
#define IDC_TPHCHOCOLATE                1035
#define IDC_EDIT4                       1036
#define IDC_TPHMIXER                    1036
#define IDC_STATICCHOCOLATE             1039
#define IDC_CANO1MIXER                  1040
#define IDC_TANQUECONGELAMENTO          1041
#define IDC_PROGRESS1                   1042
#define IDC_PROGRESSPOTE                1042
#define IDC_PROGRESSCONGELAMENTO        1043
#define IDC_TPHCONGELAMENTO             1045
#define IDC_TPHCONGELAMENTO2            1047
#define IDC_CHECKCREME                  1050
#define IDC_CHECKCHOCOLATE              1052
#define IDC_STATIC30                    1053
#define IDC_STATIC31                    1054
#define IDC_STATIC32                    1055
#define IDC_STATIC33                    1056
#define IDC_STATIC34                    1057
#define IDC_CHECKMIXER                  1058
#define IDC_CHECKCONGELADO              1059
#define IDC_COMBO1                      1060
#define IDC_COMBO_SERIAL                1060
#define IDC_MIX1                        1061
#define IDC_MIX2                        1062
#define IDC_PROGRESS2                   1063
#define IDC_SPLASH                      1064
#define IDC_CHECK2                      1067
#define IDC_CHECKRESETVOLUMES           1068
#define IDC_TEMPPHVALOR                 1104
#define IDC_STATICTPH                   1106
#define IDC_VOLUMEMIXER                 1200
#define IDC_VOLUMEMORANGO               1203
#define IDC_VOLUMECHOCOLATE             1208
#define IDC_VOLUMECREME                 1209
#define IDC_VOLUMECONGELAMENTO          1210
#define IDC_VOLUMECONGELAMENTO2         1211
#define IDC_VOLUMEPOTE                  1215
#define IDD_MAIN                        1300
#define IDC_MENU                        1301
#define IDC_PROGRESS                    1303
#define IDC_TROCARSERIAL                1304
#define IDC_VALVULAONCREME              1501
#define IDC_VALVULAONMORANGO            1502
#define IDC_VALVULAONCHOCOLATE          1503
#define IDC_VALVULAOFFCREME             1504
#define IDC_VALVULAOFFMORANGO           1505
#define IDC_VALVULAOFFCHOCOLATE         1506
#define IDC_VALVULAONCREME2             1507
#define IDC_VALVULAONMORANGO2           1507
#define IDC_VALVULAONMIXER              1507
#define IDC_VALVULAOFFCREME2            1508
#define IDC_VALVULAOFFMORANGO2          1508
#define IDC_VALVULAOFFMIXER             1508
#define IDC_VALVULAONCONGELADO          1509
#define IDC_VALVULAOFFCONGELADO         1510
#define IDC_WARNING                     1666
#define IDC_STATIC                      -1


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
